[project]
name = "semantic-kernel-summerizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ollama>=0.4.7",
    "semantic-kernel>=1.27.2",
]
